#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : happybase
Version  : 1.0.0
Release  : 17
URL      : http://pypi.debian.net/happybase/happybase-1.0.0.tar.gz
Source0  : http://pypi.debian.net/happybase/happybase-1.0.0.tar.gz
Summary  : A developer-friendly Python library to interact with Apache HBase
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: happybase-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
HappyBase
=========
**HappyBase** is a developer-friendly Python_ library to interact with Apache
HBase_.

%package python
Summary: python components for the happybase package.
Group: Default

%description python
python components for the happybase package.


%prep
%setup -q -n happybase-1.0.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
