#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : happybase
Version  : 0.9
Release  : 13
URL      : https://pypi.python.org/packages/source/h/happybase/happybase-0.9.tar.gz
Source0  : https://pypi.python.org/packages/source/h/happybase/happybase-0.9.tar.gz
Summary  : A developer-friendly Python library to interact with Apache HBase
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: happybase-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
HappyBase
=========
**HappyBase** is a developer-friendly Python_ library to interact with Apache
HBase_.

%package python
Summary: python components for the happybase package.
Group: Default

%description python
python components for the happybase package.


%prep
%setup -q -n happybase-0.9

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
